version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - ./data/mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/da
  graylog:
    image: graylog2/server:2.1.0-3
    environment:
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_WEB_ENDPOINT_URI: ${GRAYLOG_WEB_ENDPOINT_URI}
    volumes:
      - ./data/journal:/usr/share/graylog/data/journal
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:12201/udp:12201/udp"
      - "127.0.0.1:1514/udp:1514/udp"